[2023-05-02 17:41:29,241-main_hpc.py#303] [INFO] Epoch: [1][1/3] step_time: 12.782164 (12.782164)	generator_loss: 0.648907 (0.648907)	discriminator_loss: 1.385966 (1.385966)	test_loss: 0.061791 (0.061791)	train_metric: 0.339478 (0.339478)
[2023-05-02 17:41:29,242-utils.py#187] [INFO] Progress: 1 / 6 [16%], Speed: 12.782 s/iter, ETA 0:00:01 (D:H:M)

Traceback (most recent call last):
  File "/scratch/cg4177/video-frame-prediction-env/DLProject/frame_pred/src/main_hpc.py", line 344, in <module>
    train(args.cfg)
  File "/scratch/cg4177/video-frame-prediction-env/DLProject/frame_pred/src/main_hpc.py", line 197, in train
    pred_future_frames = generator(past_frames, future=num_future_frame)
  File "/ext3/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/ext3/miniconda3/lib/python3.10/site-packages/torch/nn/parallel/data_parallel.py", line 171, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/ext3/miniconda3/lib/python3.10/site-packages/torch/nn/parallel/data_parallel.py", line 181, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/ext3/miniconda3/lib/python3.10/site-packages/torch/nn/parallel/parallel_apply.py", line 89, in parallel_apply
    output.reraise()
  File "/ext3/miniconda3/lib/python3.10/site-packages/torch/_utils.py", line 644, in reraise
    raise exception
torch.cuda.OutOfMemoryError: Caught OutOfMemoryError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/ext3/miniconda3/lib/python3.10/site-packages/torch/nn/parallel/parallel_apply.py", line 64, in _worker
    output = module(*input, **kwargs)
  File "/ext3/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/scratch/cg4177/video-frame-prediction-env/DLProject/frame_pred/src/models.py", line 89, in forward
    h_t3, c_t3, m_t3 = self.STConvLSTM_Cell_3(input_tensor=h_t2, cur_state=[h_t3, c_t3, m_t2])
  File "/ext3/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/scratch/cg4177/video-frame-prediction-env/DLProject/frame_pred/src/STConvLSTM.py", line 113, in forward
    m_next = f_t_ * m_cur + i_t_ * g_t_
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 44.49 GiB total capacity; 41.67 GiB already allocated; 19.12 MiB free; 43.38 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

